### ISSUE TITLE
Client crash during sided_setup

### ISSUE THREAD

**Issue by evhub** [ConsistencyPlus/ConsistencyPlus#100]
**Describe the bug:**

Client crashes when initializing Consistency+ during sided_setup event phase. Only happens sometimes—looks like some sort of race condition.

**Versions:**
Minecraft version: 1.18.1
C+ version: 0.5.0-RC1+1.18.1-forge
Forge version: 39.0.75

**Other mods:**

See crash report: https://gist.github.com/kcwoolverton/497e1a91e80789474bbad563649bf60d

**Logs:**

Crash report: https://gist.github.com/kcwoolverton/497e1a91e80789474bbad563649bf60d

Logs: https://gist.github.com/evhub/1e7efdd0b07b0acd950feea3ee28fceb

**Comment by wafflecoffee** [comment]
oh no
