### ISSUE TITLE
Can't put flowers on grass slab

### ISSUE THREAD

**Issue by kylian-plard** [ConsistencyPlus/ConsistencyPlus#104]
Hello !
I don't know if it's supposed to be considered a bug, but when I put the grass slabs, I can't put flowers on it, like I can with grass blocks
Is it normal or just a little mistake ? :)

**Versions:**
Minecraft version: 1.18.1
Mod version : consistency_plus-0.4.3+1.18-forge

**Comment by wafflecoffee** [comment]
With a single bottom slab? You can't place things on top of single bottom slabs in vanilla, therefore we're not going to add that

If it's a top slab, well.....

**Comment by kylian-plard** [comment]
Well, I was trying with a bottom slab, but I just tried with a top slab, and same it doesn't work :/
![2022-03-11_20 09 40](https://user-images.githubusercontent.com/11462348/157935491-b8ed4778-bb27-4700-ba26-dedf8504f25c.png)

**Comment by kylian-plard** [comment]
Also, I'll just take advantage of the issue to add that I can't get dirt and grass slabs when I destroy them, even with silk touch

**Comment by Siuolthepic** [comment]
I'll try to get this done for 0.5.0

**Comment by kylian-plard** [comment]
Oh okay, it's good ;) thanks
