### ISSUE TITLE
Error loading plugin at io.github.consistencyplus.consistency_plus.CPlusWthitPluginForge 

### ISSUE THREAD

**Issue by Souldealer1962** [ConsistencyPlus/ConsistencyPlus#105]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can.  Images are often helpful, especially screenshots of the F3 debug menu.

[modloading-worker-0/ERROR]: Error loading plugin at io.github.consistencyplus.consistency_plus.CPlusWthitPluginForge
java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IBlockComponentProvider

**Versions:**
Minecraft version: 1.18.1
C+ version:
Fabric API / QSL / Forge version: Forge 39.0.19

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/8401552/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Start server (hosted)
2.
3.

**Expected behavior:**

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by Siuolthepic** [comment]
What version of WAILA out of curiousity?

**Comment by Souldealer1962** [comment]
No "mod" for Waila and curseforge only has files to 1.11
I DO have a Config folder Waila folder
Only place I see that MIGHT be a version is in logs;
at mcp.mobius.waila.Waila.loadComplete(Waila.java:108) ~[Jade-1.18-4.1.1.jar%23110!:4.1.1]

**Comment by Souldealer1962** [comment]
Found it;
Waila (Jade) 4.1.1

**Comment by Siuolthepic** [comment]
On the one hand, it seems pretty simple to fix. On the other, it means we have to go back and try to work on older versions (1.18.1) for a release.

Are you able to try to update to 1.18.2?

**Comment by Souldealer1962** [comment]
Problem is?
I'll talk to the others about 1.18.2.
I normally don't jump on the latest until the bugs have been sprayed with raid.
Only reason I used 1.18.1 was a new server after a few years away.

**Comment by Siuolthepic** [comment]
> Problem is? I'll talk to the others about 1.18.2. I normally don't jump on the latest until the bugs have been sprayed with raid. Only reason I used 1.18.1 was a new server after a few years away.

Its some minor code issues with referencing certain pieces of code. But porting between the versions is pretty annoying.
Are you able to use 0.5.0-RC1 for a bit? Theres links to it on Curseforge and Modrinth

**Comment by Souldealer1962** [comment]
Worth a try. Thanks

**Comment by Souldealer1962** [comment]
Didn't work.
Don't do sweat it yet, as I might force upgrades, unless others have the same issue
Thanks

**Comment by Cart3r1234** [comment]
Pretty sure any Wthit/waila stuff has been removed in the update we are working on, so I'm gonna close this unless it comes up again.
