### ISSUE TITLE
AbstractMinecartEntityMixin from mod consistency_plus failed injection check

### ISSUE THREAD

**Issue by Ayuma-cell** [ConsistencyPlus/ConsistencyPlus#112]
**Describe the bug:**
Minecraft fails to start due to a failed injection check. I'd go further into detail. but I don't understand the log messages enough to do so. I'm creating this issue here because of this line:

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cPlus$redirectGetOtherEntitesNubertCheck(Lnet/minecraft/class_1937;Lnet/minecraft/class_1297;Lnet/minecraft/class_238;Ljava/util/function/Predicate;)Ljava/util/List; in consistency_plus.mixins.json:AbstractMinecartEntityMixin from mod consistency_plus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap consistency_plus-common-refmap.json`

**Versions:**
Minecraft version: 1.18.2
C+ version: /
Fabric API / QSL / Forge version: QSL 1.1.0

**Other mods:**
  [✔️] 3dskinlayers-fabric-1.4.4-mc1.18.2
  [✔️] AdditionalAdditions-4.0.0
  [✔️] Adorn-3.4.0+1.18.2-fabric
  [✔️] amecs-1.3.7+mc.1.18.2
  [✔️] appleskin-fabric-mc1.18.2-2.4.0
  [✔️] architectury-4.4.56
  [✔️] badpackets-fabric-0.1.2
  [✔️] charmonium-fabric-1.18-4.0.0
  [✔️] Chunky-1.2.164
  [✔️] CITResewn-1.0.1+1.18.2
  [✔️] clickthrough-1.18.2-fabric0.47.10-0.4
  [✔️] cloth-config-6.2.57-fabric
  [✔️] cmods-1.2.0
  [✔️] consistency_plus-0.5.0+1.18.2-fabric
  [✔️] cullleaves-2.3.2
  [✔️] dashloader-def-3.1.1+1.18
  [✔️] debugify-1.9.0-fabric-1.18.2
  [✔️] denseores-1.2.2+1.18.2
  [✔️] dusk-fabric-1.18.2-1.9
  [✔️] dynamic-fps-2.1.0
  [✔️] dynview.fabric-1.18.2-2.1
  [✔️] eldritch-mobs-1.11.0
  [✔️] enhancedblockentities-0.6+1.18.2
  [✔️] entityculling-fabric-mc1.18-1.5.1
  [✔️] expandedstorage-7.3.12+1.18.2
  [✔️] extrakeybinds-1.18-0.1.0
  [✔️] fabric-language-kotlin-1.7.4+kotlin.1.6.21
  [✔️] fallingleaves-1.11.1+1.18.2
  [✔️] FallingTree-1.18.2-3.5.1
  [✔️] ferritecore-4.2.1-fabric
  [✔️] figura-0.0.8+1.18.2
  [✔️] Gobber2-Fabric-1.18.2-2.5.73
  [✔️] indium-1.0.3+mc1.18.2
  [✔️] InventoryProfilesNext-fabric-1.18.2-1.3.6
  [✔️] iris-mc1.18.2-1.2.4-build.38
  [✔️] krypton-0.1.9
  [✔️] Ksyxis-1.1
  [✔️] lazydfu-0.1.2
  [✔️] lithium-fabric-mc1.18.2-0.7.9
  [✔️] megane-7.5.1
  [✔️] Modern-Industrialization-1.1.1
  [✔️] modmenu-3.2.1
  [✔️] ninjaphenix-container-library-1.3.0+1.18-fabric
  [✔️] Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-11
  [✔️] Origins-1.18.2-1.4.1
  [✔️] origins-additionaladditions-addon-1.18-v1.1
  [✔️] Pehkui-3.3.0+1.14.4-1.19
  [✔️] pinglist-1.3.3
  [✔️] polymorph-fabric-0.0.20-1.18.2
  [✔️] PresenceFootsteps-1.5.0
  [✔️] Quilt Standard Library 1.1.0 MC-1.18.2
  [✔️] redstone-bits-1.7.1+fabric-mc1.18.2
  [✔️] reeses_sodium_options-mc1.18.2-1.4.2
  [✔️] RoughlyEnoughItems-8.1.457
  [✔️] servercore-1.2.9-1.18.2
  [✔️] sodium-extra-mc1.18.2-0.4.3
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15
  [✔️] starlight-1.0.2+fabric.89b8d9f
  [✔️] TerraBlender-fabric-1.18.2-1.1.0.99
  [✔️] ToolStats-Forge-1.18.2-9.0.1
  [✔️] worldedit-mod-7.2.10
  [✔️] wthit-fabric-4.10.1
  [✔️] Xaeros_Minimap_22.7.0_Fabric_1.18.2
  [✔️] XaerosWorldMap_1.21.2_Fabric_1.18.2
  [✔️] yosbr-0.1.1
  [✔️] YungsApi-1.18.2-Fabric-2.0.8
  [✔️] YungsBetterDungeons-1.18.2-Fabric-2.1.0
  [✔️] YungsBetterMineshafts-1.18.2-Fabric-2.1.1
  [✔️] YungsBetterStrongholds-1.18.2-Fabric-2.1.1
  [✔️] YungsBridges-1.18.2-Fabric-2.1.0
  [✔️] YungsExtras-1.18.2-Fabric-2.1.0

**Logs:**
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/8646830/latest.log)

**Comment by Ayuma-cell** [comment]
Looks like a 3-Way incompatibility between:
Consistency+
Lithium
Dash Loader

Deactivating either fixes the issue

**Comment by TropheusJ** [comment]
This is an incompatibility with lithium, which has already been fixed in development. Next release will fix it.
