### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by ChristopherHaws** [ConsistencyPlus/ConsistencyPlus#115]
Hey there, I didn't see another issue open for 1.19 support, but the 1.18.2 version doesn't seem to work with 1.19. Since the architectury mod was updated [2 days ago to support 1.19](https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/3826031), I would love to be able to use this on my 1.19 server. ^_^

Thanks again for making this amazing mod.

**Comment by Cart3r1234** [comment]
It will happen soon!

**Comment by Redd56** [comment]
Soon™️

**Comment by Flyvee** [comment]
How soon is soon? Cause one of my mods have made an awesome spawn build using consistency + and I want to transfer it to the new world when we reset the server to be 1.19 and this is the last mod we are waiting dearly for.

**Comment by Cart3r1234** [comment]
Currently we're pretty much done with the 1.18 version of 0.5.1, and then after that we'll start working on the 1.19 version.  We'll probably have a release candidate out for the 1.18 version sometime soon, and assuming no issues are found we'll move on to 1.19

**Comment by Redd56** [comment]
As i thought. soon™️ (meaning not too far off)

**Comment by Cart3r1234** [comment]
> As i thought. soon™️ (meaning not too far off)

I'd like to have everything ready by the end of the month, but we currently don't have an estimated date.  The 1.18 rc will probably be out within the next few days though because that's been tested and is pretty much ready to go.

**Comment by Redd56** [comment]
I dont mind the wait i know it can be a pain sometimes. Cough woldgen mods having to go from 1.17 to 1.18 cough.

**Comment by Cart3r1234** [comment]
For got to close this when we updated to 1.19 lol

**Comment by Redd56** [comment]
💀
