### ISSUE TITLE
Glazed terracotta

### ISSUE THREAD

**Issue by energy11a** [ConsistencyPlus/ConsistencyPlus#118]
**Block name(s) and description**

Block set for glazed terracotta: stair, wall, gate
Block set for polished glazed terracotta: stair, wall, gate

If needed, give us a description of the block you are requesting.  This can include things such as recipes, any functions it may have outside a building block, etc.

**Textures**

Regular textures.

**Additional info**
Add stonecutter recipes for glazed terracotta.
Add stonecutter recipes for polished glazed terracotta.

**Comment by Cart3r1234** [comment]
Closing this one as well since it is already planned for after 0.5.1
