### ISSUE TITLE
Cobbled End Stone should be Ender Dragon immune

### ISSUE THREAD

**Issue by goldenapple3** [ConsistencyPlus/ConsistencyPlus#119]
Cobbled End Stone should have the `#minecraft:dragon_immune` tag. The current behaviour is a significant change from Vanilla, because you can't easily use end stone during the End Dragon fight, and is also inconsistent with Consistency Plus itself, since it *does* add that tag to, say, obsidian variants, and adds "inifiniburn" tags to Cobbled Netherrack.

**Comment by Cart3r1234** [comment]
Will be fixed in the next update!
