### ISSUE TITLE
A solution to Consistency+ having 7 tabs in the creative inventory.

### ISSUE THREAD

**Issue by RDKRACZ** [ConsistencyPlus/ConsistencyPlus#12]
Please read https://github.com/Noaaan/MythicMetals/issues/30

IMO this is a must to do because 7 tabs are simply annoying.

**Comment by Siuolthepic** [comment]
This an interesting idea, definitely looking into it.

**Comment by Cart3r1234** [comment]
I really like this idea, We'll look into it.

**Comment by Cart3r1234** [comment]
I'm going to go ahead and close this for now, as its been narrowed down to 3 tabs, and we are still considering adding those side-tabs if necessary.
