### ISSUE TITLE
Colored ice can not be crafted to slabs nor stairs

### ISSUE THREAD

**Issue by energy11a** [ConsistencyPlus/ConsistencyPlus#123]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can.  Images are often helpful, especially screenshots of the F3 debug menu.

**Versions:**
Minecraft version:1.18.1
C+ version:
Fabric API / QSL / Forge version:fabric

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.
2.
3.

**Expected behavior:**

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by Cart3r1234** [comment]
This is intended.  Colored ice is deprecated in the most recent updates, and its recipes have been removed.  We may look into adding it back in a later update, but for now it is no longer craftable in survival.
