### ISSUE TITLE
Terracotta pillar does not have assigned tool

### ISSUE THREAD

**Issue by energy11a** [ConsistencyPlus/ConsistencyPlus#124]
**Describe the bug:**
Terracotta pillar breaks when mined with a pickaxe.

**Versions:**
Minecraft version: 1.18.1
C+ version:
Fabric API / QSL / Forge version: 13.3

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.
2.
3.

**Expected behavior:**

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by Cart3r1234** [comment]
Can confirm, turns out we listed "terracotta_corner_pillar" twice by accident.  Will fix in the next commit
