### ISSUE TITLE
Mineral block set

### ISSUE THREAD

**Issue by energy11a** [ConsistencyPlus/ConsistencyPlus#125]
**Block name(s) and description**

Variants for coal_block, charcoal_block, iron_block, gold_block, emerald_block, diamond_block and for netherite_block.

Coal and charcoal blocks should burn.

**Textures**
Charcoal_block should look like cracked coal_block. 
If you've made any, replace this section with images of potential textures, or images of existing blocks (whether from C+ or not) that it should look similar to.  If we have a general idea of what the block will look like, we may be more likely to add it!  Generally, you should include at least one image for blocks completely foreign to C+ and its existing block sets

**Additional info**

Currently netherite stairs does not have an assigned tool.

**Comment by Cart3r1234** [comment]
Please read [our planning boards](https://github.com/orgs/ConsistencyPlus/projects?type=beta) before making feature requests to see if what you are suggesting is already planned.  Netherite, Gold, and Iron will eventually be given full sets with oxidization, as well as charcoal blocks being added on their own.  We currently have no plans to add sets for things like coal, diamond, emerald, etc, and just plan on adding sets for the metalic mineral blocks.
