### ISSUE TITLE
[BUG] Recipe conflicts

### ISSUE THREAD

**Issue by IanSSenne** [ConsistencyPlus/ConsistencyPlus#127]
**Describe the bug:**
duplicated recipe that produce different items.

**Versions:**
Minecraft version: 1.18.2
C+ version: N/A
Fabric API / QSL / Forge version: N/A

**Other mods:**
N/A

**Logs:**
N/A

**To Reproduce:**
None, this bug was discovered statically without using Minecraft.

**Expected behavior:**
Recipes for different items should have different ingredients/shapes

**Screenshots:**
![image](https://user-images.githubusercontent.com/48780301/180107823-b84b4bda-a44d-4186-8409-653cc4f2be59.png)
![image](https://user-images.githubusercontent.com/48780301/180107829-3a334d08-c396-45b9-a5c9-45201d3ad2db.png)

**Additional info:**
### Items
 - `consistency_plus:cut_gray_concrete`
 - `consistency_plus:cut_green_concrete`
### Recipes
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\cut_gray_concrete_dyeing.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\cut_green_concrete_dyeing.json`
### Shape

| consistency_plus:cut_white_concrete | consistency_plus:cut_white_concrete | consistency_plus:cut_white_concrete |
| --- | --- | --- |
| consistency_plus:cut_white_concrete | minecraft:gray_dye | consistency_plus:cut_white_concrete |
| consistency_plus:cut_white_concrete | consistency_plus:cut_white_concrete | consistency_plus:cut_white_concrete |
### Items
 - `consistency_plus:cut_gray_concrete_gate`
 - `consistency_plus:cut_green_concrete_gate`
### Recipes
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\cut_gray_concrete_gate_dyeing.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\cut_green_concrete_gate_dyeing.json`
### Shape

| consistency_plus:cut_white_concrete_gate | consistency_plus:cut_white_concrete_gate | consistency_plus:cut_white_concrete_gate |
| --- | --- | --- |
| consistency_plus:cut_white_concrete_gate | minecraft:gray_dye | consistency_plus:cut_white_concrete_gate |
| consistency_plus:cut_white_concrete_gate | consistency_plus:cut_white_concrete_gate | consistency_plus:cut_white_concrete_gate |
### Items
 - `consistency_plus:copper_tile_wall`
 - `consistency_plus:exposed_copper_tile_wall`
 - `consistency_plus:oxidized_copper_tile_wall`
 - `consistency_plus:waxed_copper_tile_wall`
 - `consistency_plus:waxed_exposed_copper_tile_wall`
 - `consistency_plus:waxed_oxidized_copper_tile_wall`
 - `consistency_plus:waxed_weathered_copper_tile_wall`
 - `consistency_plus:weathered_copper_tile_wall`
### Recipes
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\copper_tile_wall_crafting.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\exposed_copper_tile_wall_crafting.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\oxidized_copper_tile_wall_crafting.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\waxed_copper_tile_wall_crafting.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\waxed_exposed_copper_tile_wall_crafting.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\waxed_oxidized_copper_tile_wall_crafting.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\waxed_weathered_copper_tile_wall_crafting.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\weathered_copper_tile_wall_crafting.json`
### Shape

| minecraft:cut_copper | minecraft:cut_copper | minecraft:cut_copper |
| --- | --- | --- |
| minecraft:cut_copper | minecraft:cut_copper | minecraft:cut_copper |
| ___ | ___ | ___ |
### Items
 - `consistency_plus:cyan_terracotta_wall`
 - `consistency_plus:gray_terracotta_wall`
### Recipes
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\cyan_terracotta_wall_dyeing.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\gray_terracotta_wall_dyeing.json`
### Shape

| consistency_plus:terracotta_wall | consistency_plus:terracotta_wall | consistency_plus:terracotta_wall |
| --- | --- | --- |
| consistency_plus:terracotta_wall | minecraft:gray_dye | consistency_plus:terracotta_wall |
| consistency_plus:terracotta_wall | consistency_plus:terracotta_wall | consistency_plus:terracotta_wall |
### Items
 - `minecraft:netherrack`
 - `consistency_plus:polished_netherrack`
### Recipes
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\netherrack_crafting.json`
 - `consistency_plus-0.5.0+1.18.2-forge\data\consistency_plus\recipes\polished_netherrack_crafting.json`
### Shape

| minecraft:netherrack | minecraft:netherrack | ___ |
| --- | --- | --- |
| minecraft:netherrack | minecraft:netherrack | ___ |
| ___ | ___ | ___ |

**Comment by Cart3r1234** [comment]
You are absolutely right, thank you for reporting!  This will be fixed shortly.
