### ISSUE TITLE
[Crash] 1.18.2 Crash with Radium

### ISSUE THREAD

**Issue by Reshy** [ConsistencyPlus/ConsistencyPlus#128]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can.  Images are often helpful, especially screenshots of the F3 debug menu.

**Versions:**
Minecraft version:  1.18.2
Fabric API / QSL / Forge version: 40.1.68

**Other mods:**
![image](https://user-images.githubusercontent.com/2096384/180418823-765af49a-9dee-4837-b501-88ff23fbd891.png)

**Logs:**
https://pastebin.com/iR9Ty1i1

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.  Use the given mods
2.  Launch the game

**Expected behavior:**
A crash shouldn't happen with Radium.

**Comment by Siuolthepic** [comment]
It would be more appropriate to say lithium is obscuring this bug than to say this is from Radium.

Nubert is a very stable block with 0 issues

**Comment by TropheusJ** [comment]
problematic code has been removed
