### ISSUE TITLE
Mislabeled version on modrinth

### ISSUE THREAD

**Issue by sisby-folk** [ConsistencyPlus/ConsistencyPlus#129]
Tiny issue here, [0.5.1 for fabric 1.18.2](https://modrinth.com/mod/consistencyplus/version/0.5.0%2Bfabric-1.18.2) is mislabeled as `0.5.0+fabric-1.18.2`, and isn't featured - just found it when updating through packwiz.

**Comment by wafflecoffee** [comment]
wow this page really is a mess isn't it

**Comment by wafflecoffee** [comment]
I've fixed what's mentioned in this issue, but I'm going to keep it open as there are a lot of other things I still need to do to clean up this page.

**Comment by Cart3r1234** [comment]
0.5.1 Forge also had this problem so I fixed that, and I deleted the duplicate Fabric 0.4.3, since I'm not really sure why or how that happened.  Modrinth still says the duplicate is there after deleting it though, but I assume its probably just still showing up on my end.

**Comment by wafflecoffee** [comment]
The page has now been cleaned up significantly. I'm now working on changing the URLs to specific jars so that downloads get counted correctly.
