### ISSUE TITLE
If you don't care about/have time for #12.

### ISSUE THREAD

**Issue by RDKRACZ** [ConsistencyPlus/ConsistencyPlus#13]
Temporary workaround till #12 is (hopefully) resolved. Marked as a bug because having 7 tabs is simply worse than an all-in-one tab.
![image](https://user-images.githubusercontent.com/43277609/110683801-bab2cb80-81dc-11eb-8f61-22cca25b87c5.png)
The first two and next two tabs should be merged - "Stones" + "Sandstones" and "Bricks" + "Lesser Stones". The item count won't be too big when merged, will be readable.

The same goes for Misc and Extra tabs
![image](https://user-images.githubusercontent.com/43277609/110683954-e03fd500-81dc-11eb-84d6-bbe27c4e8fad.png)
The Extra tab has just 9 items.

This way you will go from 7 to 4 tabs.

**Comment by Cart3r1234** [comment]
We will definitely keep the tabs in mind, as I agree that the number could be reduced.

**Comment by Siuolthepic** [comment]
To me, it would make more sense to go

"Stones+Lesser" "Bricks+Sandstone" "Endstone+Purpur" "Misc+Extra"

**Comment by Cart3r1234** [comment]
I'm going to go ahead and close this since the number of tabs is going to be reduced for 0.3 down to 3 (maybe 4 at most) tabs
