### ISSUE TITLE
Snow Slab recipe collides with Vanilla Snow recipe

### ISSUE THREAD

**Issue by sisby-folk** [ConsistencyPlus/ConsistencyPlus#135]
Sincere apologies for ignoring the issue template.

Anyhow the recipe for snow slabs collides with the vanilla recipe for snow
![image](https://user-images.githubusercontent.com/55819817/193514356-f154c53e-8417-47c5-a3d9-fe26e40b1f2a.png)

Here's the [recipe](https://github.com/ConsistencyPlus/ConsistencyPlus/blob/master/common/src/main/resources/data/consistency_plus/recipes/snow_slab_crafting.json)

**Comment by Cart3r1234** [comment]
Fixed in latest commit.  The snow layer recipe has been changed to 1x2 instead of 1x3 so they don't override, and the output number for the layers has been adjusted as well.
