### ISSUE TITLE
crash on QSL 

### ISSUE THREAD

**Issue by MissGamerz** [ConsistencyPlus/ConsistencyPlus#137]
**Describe the bug:**
hard crash on QSL (its fine on fabric) when making anything in the stonecutter

**Versions:**
Minecraft version: 1.19.2
C+ version: 0.5.1
QSL

**Other mods:**
Architectury: 6.2.46

**Logs:**
https://pasteio.com/xazOjz55D1IE

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. install above mods start the game
2. grab some stone
3. craft stone tiles

**Expected behavior:**
for them to craft

**Comment by GlitchSlayed** [comment]
Can confirm, having the same issue, though it doesn't happen when I turn cobble into regular stone in the stonecutter, just almost anything else though.

**Comment by magneticflux-** [comment]
This is caused by this issue: https://github.com/TropheusJ/stonecutter-recipe-tags/issues/5

**Comment by paulhlschr** [comment]
Is the fix already implemented into C+?
If not, when can we expect to see it approximately?

**Comment by magneticflux-** [comment]
There has not been a release with https://github.com/TropheusJ/stonecutter-recipe-tags/pull/6 included yet.

**Comment by sisby-folk** [comment]
Hey gang, just wanted to flag that this mod is still unusable on quilt as I figure y'all are working on some big update - so I went in and built a11e3c0 as a stand-in until the update (though not sure if that'll be on 1.19.2, so good as a backup) [consistency_plus-fabric-0.5.2+1.19.2.jar](https://github.com/sisby-folk/mc-packs/blob/quilt_1.19.2_plus/mods/consistency_plus-fabric-0.5.2+1.19.2.jar)

Definitely doesn't crash when cutting stone at least.
