### ISSUE TITLE
[Useless issue] Some blocks are missing recipes.

### ISSUE THREAD

**Issue by RDKRACZ** [ConsistencyPlus/ConsistencyPlus#14]
In the middle of writing this report, I remembered that ~~I'm dumb~~ you already know about this "NOTE: 0.2.0 is missing quite a few crafting recipes..."

But I decided to report it anyway just in case someone else would forget about it and try to report it.

Using REI I was able to find out that
<details>

cut_diorite +_slab/stairs/wall
diorite_bricks
granite_bricks
cracked/mossy_chiseled_blackstone
cracked_
cracked_carved_blackstone
Probably way more

</details>
are missing recipes (left clicking doesn't show a recipe)

**Comment by RDKRACZ** [comment]
Seems like cracked carved blackstone and andesite still don't have recipes. Other blocks mentioned above are fixed. Btw no cracked carved granite and diorite?

**Comment by Siuolthepic** [comment]
Thanks for the reports on those. 

Ill round out some of the ones I know dont have recipes yet to fix in RC-0.2.0

Colored Glowstone/Ice
Terracotta and Glowstone walls
And the two you mentioned.

Thats real impressive that I got most of them though.

**Comment by Siuolthepic** [comment]
Im going to move this to #32. I want to focus on overall data issues in that one.
