### ISSUE TITLE
Mods page "Website" button sends you to the wrong URL

### ISSUE THREAD

**Issue by aaronhowser1** [ConsistencyPlus/ConsistencyPlus#140]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can.  Images are often helpful, especially screenshots of the F3 debug menu.

**Versions:**
C+ version: consistency_plus-fabric-0.5.1+1.19.2

![image](https://user-images.githubusercontent.com/15698722/206822174-280ce469-90ac-4b17-b455-c490d72519e8.png)

Sends you to https://www.curseforge.com/minecraft/mc-mods/consistency instead of https://www.curseforge.com/minecraft/mc-mods/consistencyplus

**Comment by Cart3r1234** [comment]
Thanks for pointing this out!  We thought we'd corrected all of the links after changing our curseforge slug, but forgot to update the one actually in the mod.  I just fixed it in a commit, but will leave the issue open until we release the next update.

**Comment by Cart3r1234** [comment]
Closing this now since its been fixed for a while and the next update is being worked on.
