### ISSUE TITLE
C+ Copper blocks do not oxidize

### ISSUE THREAD

**Issue by Cart3r1234** [ConsistencyPlus/ConsistencyPlus#142]
**Describe the bug:**
C+ Copper blocks do not oxidize anymore.  It is unknown what update caused them to stop oxidizing. 

**Versions:**
Minecraft version: 1.19.2
C+ version: Fabric/Quilt 0.5.1+1.19.2
QSL version: qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2

**Other mods:**
https://modrinth.com/modpack/devos-season-5 (untested with just C+; could be an incompatibility)

**To Reproduce:**

1. Place a C+ copper block
2. Sit incredibly still for an indeterminable amount of time
3. Assuming you have not died of thirst or starvation, observe that the copper has not oxidized.

**Expected behavior:**
The copper should oxidize.

**Screenshots:**
![image](https://user-images.githubusercontent.com/69820300/210498723-391c709a-e313-42f1-9d56-a359dea5a849.png)
 
**Additional info:**
Could be an incompatibility because I first noticed this while playing a modpack.  Even if that is the case, it should be looked into and fixed.

**Comment by asoji** [comment]
when did carter become a minecraft children-focused youtuber

**Comment by Cart3r1234** [comment]
But first a word from our sponsor

**Comment by Cart3r1234** [comment]
Interestingly using a build that has post-0.5.1 commits fixes this.  Gonna leave the issue open until we release another update though

**Comment by Cart3r1234** [comment]
> Interestingly using a build that has post-0.5.1 commits fixes this. Gonna leave the issue open until we release another update though

Turns out the situation is even weirder - updating to a post-0.5.1 build on a client and server caused all of the already placed C+ copper blocks to jump forward 3-4 oxidization stages, but then everything stopped oxidizing again entirely.

**Comment by Cart3r1234** [comment]
Fixed in the registry redo
