### ISSUE TITLE
Stonecutter won't output more than 1 item.

### ISSUE THREAD

**Issue by Ritter888** [ConsistencyPlus/ConsistencyPlus#143]
Minecraft 1.19.2 Fabric API (No other mods)

Stonecutter won't output more than 1 resulting item.

Just spent over an hour figuring out which of my 200 mods are causing this.

**Comment by TropheusJ** [comment]
what version of C+

**Comment by Cart3r1234** [comment]
Jay the only 1.19.2 version we have is 0.5.1

**Comment by Ritter888** [comment]
Correct, that's the mod version I have.

**Comment by Cart3r1234** [comment]
Are you using the released version or a build from one of our more recent commits?  I tested the fabric/quilt release build of 0.5.1 yesterday and couldn't get the issue to happen, but have ran into it on more recent dev builds.
