### ISSUE TITLE
[BUG] Crash with ConsistencyPlus and DramaticDoors on Quilt

### ISSUE THREAD

**Issue by DaveyL2013** [ConsistencyPlus/ConsistencyPlus#146]
**Important Information**
Minecraft Version: **1.19.2**
Quilt Version: **0.18.1-beta.58**
DramaticDoors Version: **Fabric-1.19.2-1.4.0**
C+ Version: **fabric-0.5.1+1.19.2**

**Describe the bug**
Having both ConsistencyPlus and DramaticDoors installed on Quilt causes Minecraft to fail to load due to minecraft:air having a duplicate waterlogged property... *somehow*

**To Reproduce**
Install Quilt
Install ConsistencyPlus and DramaticDoors (+ QSL & Architectury, tested both with and without other unrelated mods)
Try to start Minecraft

**Expected behavior**
The game... *doesn't* crash from the air being to moist <sub><sup>(that's a joke obviously)</sup></sub>

**Logs**
https://mclo.gs/QFLPaEp

**Comment by DaveyL2013** [comment]
Paired Issue: https://github.com/Kitteh6660/DramaticDoors/issues/16

**Comment by TropheusJ** [comment]
issue with Dramatic Doors, this will crash with any mod that adds waterloggable doors or fence gates.

**Comment by TropheusJ** [comment]
supposedly fixed
