### ISSUE TITLE
Some unique block suggestions.

### ISSUE THREAD

**Issue by RDKRACZ** [ConsistencyPlus/ConsistencyPlus#15]
Well, some of these suggestions aren't here for the reasons of adding more consistency but I would lobe to see them. Textures aren't mine.

* Dirt, Netherrack, Basalt, Glass Slab and Stairs

* Dirty Cobblestone - it could generate naturally between dirt and stone. Should like nice in some buildings.
![image](https://user-images.githubusercontent.com/43277609/110706943-e2b02800-81f8-11eb-9f66-8857d325cf15.png)

* Carved Melon
![image](https://user-images.githubusercontent.com/43277609/110707173-37ec3980-81f9-11eb-965a-299da8bf4cea.png)

* Rope - is climbable - placement works like in chains - needs some block to hang from it.
![image](https://user-images.githubusercontent.com/43277609/110707397-826db600-81f9-11eb-806f-6022b413b8d1.png)

* Fence doors
![image](https://user-images.githubusercontent.com/43277609/110707538-bba62600-81f9-11eb-8168-60c44c5c7fce.png)

* Concrete layers
![image](https://user-images.githubusercontent.com/43277609/110707636-dd071200-81f9-11eb-892a-3633764c5866.png)

* Doors with a window
![image](https://user-images.githubusercontent.com/43277609/110707882-38390480-81fa-11eb-838d-6af973979065.png)

* Carpeted stairs
![image](https://user-images.githubusercontent.com/43277609/110713934-07110200-8203-11eb-8db0-50516441247c.png)

* Quarter slab
![image](https://user-images.githubusercontent.com/43277609/110714078-3b84be00-8203-11eb-94f9-27f97ba93883.png)

* Quarter stairs
![image](https://user-images.githubusercontent.com/43277609/110714154-60793100-8203-11eb-9854-ad00406d3731.png)

* Flint Block
![image](https://user-images.githubusercontent.com/43277609/110757728-005aad00-824c-11eb-92a4-be2a55d72f64.png)

* Planks variants
![image](https://user-images.githubusercontent.com/43277609/111066871-8c293f00-84c1-11eb-9c6d-0b3601286b33.png)

* More flower pots
![image](https://user-images.githubusercontent.com/43277609/111713529-1ec63700-8850-11eb-9582-1a46b23aafc2.png)

* Soul Glass
![image](https://user-images.githubusercontent.com/43277609/113892739-9b509380-97c6-11eb-9c24-4c4d75ad0fd2.png)

* Furnaces from all stones
![image](https://user-images.githubusercontent.com/43277609/114452025-405cd900-9bd8-11eb-8f2c-a81da37303c3.png)
 
* Wooden tools created from Crimson and Warped Wood. 
![image](https://user-images.githubusercontent.com/43277609/114453333-b746a180-9bd9-11eb-85db-750ab0ffd988.png)

* Stone tools crafted from Granite, Diorite, Andesite, Sandstone, Red Sandstone, Blackstone, Basalt.
![image](https://user-images.githubusercontent.com/43277609/114453413-c7f71780-9bd9-11eb-9748-9f6a93627f10.png)

* Bamboo blocks and items... bamboo is so useless in vanilla :(
![image](https://user-images.githubusercontent.com/43277609/114454120-89159180-9bda-11eb-949b-3ca4191eba2b.png)

* Wooden Bucket

* Gold Bar

* Gold and Redstone Lantern

* Tiles/Paths
![image](https://user-images.githubusercontent.com/43277609/117030658-2490b280-ad00-11eb-8073-0895d9e62c2f.png)
![image](https://user-images.githubusercontent.com/43277609/117030719-32463800-ad00-11eb-93ae-1cec3ad85792.png)
![image](https://user-images.githubusercontent.com/43277609/117030732-35412880-ad00-11eb-8c56-0fc980e96bdd.png)

**Comment by Siuolthepic** [comment]
Thank you for the suggestions! We will probably note some of these for later. Feel free to share more suggestions

**Comment by Cart3r1234** [comment]
I really like the idea of fence-style doors

**Comment by RDKRACZ** [comment]
Hi, just wanted you to know I updated this list a few times, also may I ask if some of these blocks were accepted?

**Comment by Siuolthepic** [comment]
We will probably be adding some of these in the future, yes. But this will be post 0.3 or even post 1.0.0

**Comment by Cart3r1234** [comment]
Revisiting this -
- Tiles will be a part of 0.4, and are just a new building variation coming to all block sets.  "Cut" has been split into Cut and Tiles
- Carved Melons are probably going to happen sometime after 0.4
- Flint, Gunpowder, and Charcoal blocks are planned
- Soul Glass will probably happen at some point
- Dirty, Snowy, and Sandy versions of blocks will likely be an addon we make once our addon system is implemented
- We may look into some of the wood-based suggestions with a wood addon, since most of the Materials covered by C+ are stones or other inorganic substances. 
Everything not mentioned, but in the list, will likely not happen within the next few updates, but could happen sometime later down the line.

**Comment by DeathByAutoscroll** [comment]
The extra furnaces would be cool
