### ISSUE TITLE
The ice slab and packed ice slab variants aren't slippery.

### ISSUE THREAD

**Issue by Flyvee** [ConsistencyPlus/ConsistencyPlus#151]
**Describe the bug:**
The slabs of the ice and packed ice are like normal slabs in that they lose their slipperiness.
**Versions:**
Minecraft version: 1.19.2
C+ version: Where do I see that?
Fabric API / QSL / Forge version: 0.73.2

**Other mods:**
![image](https://user-images.githubusercontent.com/30793646/218340796-4668495d-98b0-459c-9c4f-105c52b89970.png)
![image](https://user-images.githubusercontent.com/30793646/218340821-8f7c41eb-2076-4110-bc40-7cdb935480b3.png)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Place Ice slab down.
2. Walk onto ice.
3. Don't slip when you stop walking.

**Expected behavior:**
As it is still made of ice, just cut in half. It is expected to still keep the slipperiness feature.

**Comment by Cart3r1234** [comment]
Fixed in 0.5.2-rc.1
