### ISSUE TITLE
Server-Console language bug "menu.preparingSpawn"

### ISSUE THREAD

**Issue by SgtKaneki** [ConsistencyPlus/ConsistencyPlus#152]
**Describe the bug:**
if Consistency+ is installed there are a few language-bugs at the server-console.
For example: "menu.preparingSpawn"

**Versions:**
Minecraft version: 1.19.2
Fabric API / QSL / Forge version: Fabric 0.14.14

**Other mods:**
Doesn't matter, even happens if only consistency+ (and "architectury" as required) if installed.

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Just install Consistency+ on a Fabric Server
2. Start the Server

**Expected behavior:**
Should not affect the "language" ^^

**Comment by TigerWalts** [comment]
The mod file contains an `assets/minecraft/lang/en_us.json` file which ends up replacing the vanilla Minecraft language file.

It is not merged.

This means that all the logging format strings are missing and you end up with just the format string's id being logged.

A quick workaround is to remove that file from the Jar.

---

For linux users you can quickly identify mods that have this file with:

```bash
for f in *.jar; do unzip -l $f | grep -q assets/minecraft/lang/en_us.json && echo $f; done
```

You can remove the file with:

```bash
zip -d <jar_file> assets/minecraft/lang/en_us.json
```

**Comment by Cart3r1234** [comment]
This should be fixed in our most recent update - the changes we make to vanilla lang strings have been moved to a built in resource pack.
