### ISSUE TITLE
Smooth Clay walls don't merge together

### ISSUE THREAD

**Issue by Flyvee** [ConsistencyPlus/ConsistencyPlus#154]
**Describe the bug:**
The smooth clay wall variant stays as single wall poles when placed next to each other.
![2023-03-11_19 52 44](https://user-images.githubusercontent.com/30793646/224504189-214e7bd0-1504-488a-9bf6-9ac4cb2f3a98.png)

**Versions:**
Minecraft version: 1.19.2
C+ version: How to get?
Fabric API / QSL / Forge version:  0.73.2 fabric api

**Other mods:**
A lot of small ones (non affecting walls), and origins, additional additions, better end and minecraft comes alive as the big ones.

**Logs:**
*Even if the game does not crash they may be useful!*
There is nothing in the logs about the walls at all.

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Place one smooth clay wall.
2. Place another smooth clay wall right next to it.
3. They stay as poles instead of forming a wall.

**Expected behavior:**

**Screenshots:**
![2023-03-11_19 52 44](https://user-images.githubusercontent.com/30793646/224504189-214e7bd0-1504-488a-9bf6-9ac4cb2f3a98.png)
![2023-03-11_20 00 48](https://user-images.githubusercontent.com/30793646/224504431-5f7821fc-a4b1-4513-99b7-1bce33559497.png)
![2023-03-11_20 00 58](https://user-images.githubusercontent.com/30793646/224504440-f98ea15a-8c47-4541-b4d2-b5ca60e93620.png)

**Comment by Cart3r1234** [comment]
This has been fixed for the next update.  They were missing from the walls tag.
