### ISSUE TITLE
coloured glowstone can't be used to charge a respawn anchor

### ISSUE THREAD

**Issue by tovc** [ConsistencyPlus/ConsistencyPlus#155]
glowstone stairs/slabs also can't be used to charge a respawn anchor, but each block is worth a non-standard amount of glowstone, so that might be intentional

coloured glowstone seems like it should be able to charge anchors

**Comment by Cart3r1234** [comment]
This is a valid bug, however dyed glowstone is likely going to be removed from the mod in the next update.  Until then I'll leave the issue open.

**Comment by Cart3r1234** [comment]
Closing this as fixed; after removing dyed glowstone we added a block set for regular glowstone, and those blocks now charge respawn anchors
