### ISSUE TITLE
Has this mod been abandoned?

### ISSUE THREAD

**Issue by allanonmage** [ConsistencyPlus/ConsistencyPlus#156]
Based on the Github insights, publish frequency, continual "we have plans for that feature" commentary, over-articulated dev speak, and other data I was able to find online, I suspect that this mod has been abandoned.

**Comment by ParanormalChicken** [comment]
No, everyone just has lives to live.
Be patient.

**Comment by triphora** [comment]
For the record. I'm not involved much in this mod's development anymore. But the team members are all alive and well (to my knowledge). Everyone is just busy in their own ways, whether it be with work, school, etc.

**Comment by Cart3r1234** [comment]
What triphora said is correct.  C+ hasn't been abandoned, but most of the team is currently occupied with other things.  The next update has been nearly ready for quite some time, but we have no ETA.
