### ISSUE TITLE
Depending on a broken library on forge.

### ISSUE THREAD

**Issue by ripSquid** [ConsistencyPlus/ConsistencyPlus#158]
https://github.com/TropheusJ/stonecutter-recipe-tags/issues/7
Related to this issue. 
ConsistencyPlus depnds on a library/mod which doesn't seem to be updated and also has an error which means it is incompatible with other mods.
(1.19.2)

**Comment by Siuolplex** [comment]
JAY FIX YO MOD

**Comment by Cart3r1234** [comment]
If I'm not mistaken, the SCRT dependency for all 3 loaders needs to be updated because it also causes issues on Quilt that have been fixed in a more recent SCRT version.

**Comment by Siuolplex** [comment]
Do we really need recipes

**Comment by asoji** [comment]
nah theyre cosmetic

**Comment by Cart3r1234** [comment]
> nah theyre cosmetic

_Well boys we, did it!  Incompatibilities are no more!_

**Comment by Cart3r1234** [comment]
I believe this has also been fixed in dev and will be resolved in the next release.
