### ISSUE TITLE
Using the stonecutter causes the client to crash.

### ISSUE THREAD

**Issue by jadelily18** [ConsistencyPlus/ConsistencyPlus#162]
**Describe the bug:**
When using the stonecutter, turning **cobbled andesite** into **andesite** causes the game to crash when you click on the andesite in the output box. This was originally apparent to me in my modpack, which I also had reports of a crash when turning **deepstone bricks** into **deepstone brick slabs**. On a server, this only crashes the client.

**Versions:**
Minecraft version: 1.19.2
C+ version: 0.5.1
Fabric API / QSL / Forge version: QSL 4.0.0-beta.30+0.76.0-1.19.2
Quilt Loader version: 0.19.0-beta.13

**Other mods:**
None! Tested on a clean Prism instance with only Architectury, QSL, & C+.

**Logs:**
https://mclo.gs/n6CGe2n

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Open stone cutter
2. Place **cobbled andesite** into the input box
3. Select **andesite**
4. Click the andesite in the output box

**Expected behavior:**
Should turn into andesite without crashing the game.

**Additional info:**
Please let me know if you need any more information!

**Comment by TropheusJ** [comment]
Fixed in dev
