### ISSUE TITLE
Warped/Crimson Nylium dropping Netherrack

### ISSUE THREAD

**Issue by Lucky-56** [ConsistencyPlus/ConsistencyPlus#165]
**Describe the bug:**
both `Warped Nylium` and `Crimson Nylium` both drop `Netherrack` when mined, expected `Cobbled Netherrack` for consistency

**Versions:**
Minecraft version: 1.18.2
C+ version: 3.2
Forge version: 40.2.2

**Other mods:**
[modlist.html.zip](https://github.com/ConsistencyPlus/ConsistencyPlus/files/11473758/modlist.html.zip)

**Logs:**
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/11473761/latest.log)
[launcher_log.txt](https://github.com/ConsistencyPlus/ConsistencyPlus/files/11473763/launcher_log.txt)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Find or place `Warped Nylium` / `Crimson Nylium`.
2. Mine it.
3. Collect the block drops.

**Expected behavior:**
`Warped Nylium` and `Crimson Nylium` to drop `Cobbled Netherrack` for consistency

**Screenshots:**
![2023-05-15_04 46 16](https://github.com/ConsistencyPlus/ConsistencyPlus/assets/55949451/30e4fd06-01f9-42cc-a08e-047e1e1e4e62)
![2023-05-15_04 46 24](https://github.com/ConsistencyPlus/ConsistencyPlus/assets/55949451/23b88bee-a072-44b1-9532-716fd9e7afa0)

**Comment by Cart3r1234** [comment]
Fixed in latest commit, thanks for the report.
