### ISSUE TITLE
Crash: Multiple Entries With The Same Key

### ISSUE THREAD

**Issue by PoggChamp** [ConsistencyPlus/ConsistencyPlus#180]
**Describe the bug:**
The game crashes whenever I place/am near either an exposed cut copper slab or a weathered cut copper slab.

**Versions:**
Minecraft version: 1.19.2
C+ version: consistency_plus-forge-0.5.2-rc.2+1.19.2.jar
Fabric API / QSL / Forge version: 43.2.12

**Other mods:**
![image](https://github.com/ConsistencyPlus/ConsistencyPlus/assets/86542146/252b13ba-6179-4ce6-a396-1f42544f25a2)

**Logs:**
*Even if the game does not crash they may be useful!*
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/12064925/latest.log)
[debug.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/12064928/debug.log)
[crash-2023-07-16_14.39.12-client.txt](https://github.com/ConsistencyPlus/ConsistencyPlus/files/12064938/crash-2023-07-16_14.39.12-client.txt)
could not find launcher_log, using PrismLauncher.

**To Reproduce:**

1. Join World.
2. Place Weathered Cut Copper Slab or Exposed Cut Copper Slab (or load a chunk with either block).

**Expected behavior:**
Expected the block(s) to render and the game not to crash

**Screenshots:**
none other than the modlist from earlier.

**Additional info:**
none.

**Comment by Cart3r1234** [comment]
This has been fixed in dev, a release with the fix will be out soon.
