### ISSUE TITLE
Missing Blocks with 1.20.1

### ISSUE THREAD

**Issue by A5ho9999** [ConsistencyPlus/ConsistencyPlus#181]
**Describe the bug:**
Well some blocks appear to be missing, major notable ones are the coloured Glowstone variants, the coloured blocks themselves as well all the block variants for them

**Versions:**
Minecraft version: 1.20.1
C+ version: https://modrinth.com/mod/consistencyplus/version/0.5.2-rc.3+1.20.1-fabric
Fabric API: https://modrinth.com/mod/fabric-api/version/0.86.1+1.20.1

**Other mods:**
In Log below

**Logs:**
Not of use (I've checked and no issues from c+) but here (ignore all the errors from other devs forgetting things, myself included)
https://gist.github.com/A5ho9999/7c113078ff6283bb2db973243303d739

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Launch Game with Mod
2. Find Block
3. Fail to find Block

**Expected behavior:**
To have the blocks?

**Screenshots:**
![spent 10 minutes trying to remember how to format screenshots](https://media.discordapp.net/attachments/970570664895463495/1138684781958279258/Screenshot_711.png)

Should have (From 1.19.2)
![1.19.2](https://media.discordapp.net/attachments/970570664895463495/1138672283234345020/image.png)
![1.19.2-2](https://media.discordapp.net/attachments/970570664895463495/1138671871815065611/image.png)

**Additional info:**
Someone is complaining to me that they are missing so now I must make issues

**Comment by Cart3r1234** [comment]
Dyed glowstone's removal is intentional.  In the 0.5.2 betas we removed any deprecated blocks and blocks that don't really fit the mod anymore.
