### ISSUE TITLE
Crash on Quilt Server 1.20.1

### ISSUE THREAD

**Issue by DaveyL2013** [ConsistencyPlus/ConsistencyPlus#182]
**Describe the bug:**
Attempting to start a quilt server with the mod on 1.20.1 crashes on startup.

**Versions:**
Minecraft version: 1.20.1 with Quilt Loader 0.20.0-beta.11
C+ version: 0.5.2-rc.3+1.20.1
Fabric API / QSL / Forge version: qfapi-7.1.1_qsl-6.1.1_fapi-0.86.1_mc-1.20.1

**Other mods:**
None needed

**Logs:**
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/12318289/latest.log)

**Comment by Cart3r1234** [comment]
Based on the log it doesn't seem like you're using [Architectury](https://modrinth.com/mod/architectury-api/version/9.1.12+fabric), which you also need for Consistency+

**Comment by DaveyL2013** [comment]
Conclusion: Architectury wasn't in fabric.mod.json so I didn't realize it was a dependency
