### ISSUE TITLE
Compatablility for Forge 47.2.1

### ISSUE THREAD

**Issue by KPaXz** [ConsistencyPlus/ConsistencyPlus#184]
**Additional info:**

Running a set of 1.20.1 mods and this mod ConsistencyPlus is not compatible with the latest Forge 47.2.1. The other 125 mods are.

**Comment by faultycore** [comment]
In case you or someone else still needs this, I just tested it and it seems to work fine with Forge 47.2.0 at least. All you need to do is open the jar archive with something like 7zip and edit Forge version range in META-INF/mod.toml.

**Comment by KPaXz** [comment]
thank you
