### ISSUE TITLE
[BUG] Carved Purpur should be Carved Purpur Block.

### ISSUE THREAD

**Issue by RDKRACZ** [ConsistencyPlus/ConsistencyPlus#25]
Same for the id, as for now it's `block.consistency_plus.carved_purpur`.

**Comment by Siuolthepic** [comment]
We may be willing to change the lang, but not the id.

Id changing without Datafixers is very very unsafe and cursed, and I dont want PDSD.

**Comment by RDKRACZ** [comment]
I don't know what are datafixers etc but from my understanding... It's Your mod so it _should_ be easy. Here is a screenshot, it... it looks inconsistent.
Github is broken and won't let me to paste **this one** image so https://imgur.com/a/4TDd5oJ

**Comment by Siuolthepic** [comment]
Sadly, should does not equal is.
Theres two ways to change an idem ID in Minecraft.

1. Mixin into Identifier, which sounds easy, but it isnt as easy and is VERY, VERY unsafe.

2. Make a Datafixer, which is what Mojang does. However, currently, mods are unable to do that.

So thats where we are at. Fun stuff. (Also, could you post the imgur images on Discord, I cant see them while at school. )
