### ISSUE TITLE
[Important] Licensing Error.

### ISSUE THREAD

**Issue by Siuolthepic** [ConsistencyPlus/ConsistencyPlus#30]
**Licensing Error**
We have recently learned that the GPLv3 license is not applicable for this mod. As due to one of the lines in the GPL License, we cannot link it with Minecraft. We will be swapping the mod from GPL to LGPL. And we need all contributors to sign off on this.

@Cart3r1234 (Approved)
@IMS212 (Approved)
@RDKRACZ 
@Deviouslrd (Approved)
@TropheusJ (Approved)
@HiItsDevin (Approved)
@DragonEggBedrockBreaking 
@DigitalTech518 (Approved)

All previous releases will also be rereleased under the LGPLv3 license.
Until this issue is resolved, I recommend ceasing contributions to this repo. Once this is fixed you may go and contribute some more.

Also, for the record, I obviously approve of the change.
Furthermore, for DragonEgg and myself, this also applies to Obby Slabs.

**Comment by DigitalTech518** [comment]
I approve

**Comment by HiItsDevin** [comment]
I approve of the changes.

**Comment by Cart3r1234** [comment]
I approve

**Comment by imyetihearmeroar** [comment]
I approve

**Comment by IMS212** [comment]
Approved

**Comment by TropheusJ** [comment]
I approve

**Comment by Deviouslrd** [comment]
![Approved](https://imgur.com/GJ8ONa5.gif)

**Comment by Siuolthepic** [comment]
With Devious' approval now in order. We will start re-releasing 0.1 and 0.2.

**Comment by DigitalTech518** [comment]
Lol, I didn't know gifs were possible in github

**Comment by wafflecoffee** [comment]
Remember to update the Modrinth page (and CF page I guess) with the proper license once the changes have gone through :wink:

**Comment by RDKRACZ** [comment]
I approve

**Comment by DragonEggBedrockBreaking** [comment]
I approve

**Comment by Siuolthepic** [comment]
That makes everyone! Ill be changing our license in just a moment and you can feel free to commit once again.

> Remember to update the Modrinth page (and CF page I guess) with the proper license once the changes have gone through 😉

Updating those will be soon.

**Comment by wafflecoffee** [comment]
> Updating those will be soon.

@Siuolthepic Soon :tm: 
(it never happened on Modrinth)

**Comment by Siuolthepic** [comment]
You see, the mod shipped with lgpl, and it should be updated from custom to lgpl
