### ISSUE TITLE
[Bug] Data Issues

### ISSUE THREAD

**Issue by Siuolthepic** [ConsistencyPlus/ConsistencyPlus#32]
**Description**
The internal datapack for C+ as of 0.3, is not perfect. It was mostly fixed but there is still problems.
Most noteably, there are a few major issues

1. No Advancements for certain Recipes
2. Recipes are missing for certain blocks, while for other vanilla ones they overlap.

Furthermore, we could use the tags for other mods for better compat in some regards.

A specific list is coming later.

**Versions**
Minecraft version: 1.16.5
C+ version: 0.3
Fabric API version: Any

Im self assigning this, if any other members or contributors want to fix this feel free.

**Comment by Cart3r1234** [comment]
> Im self assigning this, if any other members or contributors want to fix this feel free.

I might take a stab at fixing the advancement stuff with the recipes we currently have; if we put every recipe for one block type under one advancement, we can use that as a reference to what recipes we are missing, and if we want we can split the advancement once all recipes are completed

**Comment by Siuolthepic** [comment]
> I might take a stab at fixing the advancement stuff with the recipes we currently have; if we put every recipe for one block type under one advancement, we can use that as a reference to what recipes we are missing, and if we want we can split the advancement once all recipes are completed

The thing is that Im concerned with is less if it is missing resources, and more if its overlapping with vanilla recipes (This I edited into the issue to make it more clear.)

As for advancements. That isnt too worrying.

**Comment by Cart3r1234** [comment]
The overlapping recipes aren't a problem as long as we put them in the right folder; we had quite a few overlapping ones before with no problem

**Comment by TropheusJ** [comment]
just bundle polymorph :bigbrain:

this is a joke

**Comment by Cart3r1234** [comment]
Closing this since we've basically done everything for 0.4
