### ISSUE TITLE
0.4 Release Goals

### ISSUE THREAD

**Issue by Siuolthepic** [ConsistencyPlus/ConsistencyPlus#35]
0.4 Release Goals

- [X] Support for Deepslate, Calcite, Tuff, and Dripstone
- [X] Finish the Grass block varients.
- [x] Fix the recipes.

**Comment by Siuolthepic** [comment]
1.17 Release date will not be met, moving back a week or two.

**Comment by Cart3r1234** [comment]
_We could try aiming for June 22nd :trollface:_

**Comment by Deviouslrd** [comment]
:antiwheeze:

**Comment by OptiFox** [comment]
so true

**Comment by Siuolthepic** [comment]
I swear to god Carter this is why I wanted an answer to Jay's question earlier
![image](https://user-images.githubusercontent.com/43890828/121104748-4a5e1b00-c7c8-11eb-9dc9-6238305709d3.png)

**Comment by Cart3r1234** [comment]
We do a mediocre amount of trolling :trollface:

**Comment by Cart3r1234** [comment]
I guess we can close this now?  We've hit all the checkboxes aside from the stuff that got moved to 1.0
