### ISSUE TITLE
Split the mod between consistency and consistency/extras

### ISSUE THREAD

**Issue by MeeniMc** [ConsistencyPlus/ConsistencyPlus#37]
**Feature**

I really like the core idea of this mod: adding the missing stairs/pillars to existing blocks.

I am not super excited about the 'dye' types of blocks (at least not all of them), and I'd rather not have them. 

The obvious solution is to split the mod in 2 or more parts, 

1. The core, "non-controversial" type of blocks (I'm sure defining that set will have no controversy at all :D)
2. The extras (1 or more additional sub-mods) with the special blocks
  a. Soulstone blocks
  b. Concrete/Terracotta (they could go in core IMO)
  c. Glowstones colors
  d. Ice colors
  e. warped blocks

**Alternatives**

Have some config file to whitelist/blacklist some blocks and full block families

```
blacklist=*Glowstone*, Mossy*blackstone, Grass Wall
```

**Comment by Cart3r1234** [comment]
Some way to disable certain block sets is planned, although it is not final yet.  We have been discussing both methods, splitting it into modules, and having a config, but no final decision has been made.  

And regarding the dyed ice and glowstone, yeah those were kinda thrown in there last minute just because and were never really meant to be treated as serious blocks lol ¯\_(ツ)_/¯

**Comment by Siuolthepic** [comment]
Let me detail our plans as of right now under a project named Project Satella

Currently, we plan to have both in a sense. 
We plan to have a modular system, with 3 main module types.
1. Core, which will contain all of the shared code, models, and the alike for the mod.
2. Base (Name pending), which will contain all of the normalish blocks for the mod.
3. Extras, which will contain all of the wacky blocks for the mod.

Things like the ice and glowstone probably would end up in Extras, whilst more normal things like Warped Bricks, Concrete/Terracotta, and Soul Sandstone will all end up in regular.

Furthermore, we also plan to add a config file with atleast block disabling, theres a low chance but if I can figure out how I will add a block settings definition thingy in there.

I am quite amused by the fact that you were able to guess a majority of the ideas that the upper staff has correctly.

**Comment by Cart3r1234** [comment]
Gonna go ahead and close this since our plans have moved away from doing this.  Will reopen if/when we reconsider, but for the time being we no longer plan on splitting the mod, but instead will eventually have a config that serves a similar purpose.
