### ISSUE TITLE
Update modrinth desc.

### ISSUE THREAD

**Issue by Samisaprogrammer** [ConsistencyPlus/ConsistencyPlus#38]
**Describe the bug**
The modrinth description is still stuck on 0.1.0

**Versions**
N/A

**Other mods**
N/A

**Logs**
N/A

**To Reproduce**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Visit modrinth
2. Look at description
3. There is no step 3

**Expected behavior**
The description is the same or similar to curseforge

**Screenshots**
![image](https://user-images.githubusercontent.com/59611020/124288901-3ac0c080-db41-11eb-95ed-9cc2157ef4f6.png)
![image](https://user-images.githubusercontent.com/59611020/124288976-4dd39080-db41-11eb-92ef-c8d716508304.png)

**Comment by Siuolthepic** [comment]
Alright, I'll try to fix this when I get home.

**Comment by wafflecoffee** [comment]
> Alright, I'll try to fix this when I get home.

I would have done this already but only @IMS212 has permissions to, he should give us permissions more than just add version :irritat:

**Comment by Siuolthepic** [comment]
I have updated the description, thanks for the report!
