### ISSUE TITLE
Can't craft quartz block

### ISSUE THREAD

**Issue by mj717** [ConsistencyPlus/ConsistencyPlus#39]
**Describe the bug**
When this mod adds a recipe for Polished Quartz, it's the same recipe as the vanilla Block of Quartz. The game defaults to the modded recipe and I've been unable to get normal quartz blocks. I would really like to be able to craft both polished and normal quartz blocks.

**Versions**
Minecraft version: 1.17
C+ version: 0.3.3
Fabric API version: 0.36.0

**Other mods**
Not really relevant to this situation. Will add if asked.

**Logs**
Not really relevant to this situation. Will add if asked.

**Comment by Cart3r1234** [comment]
This is a known bug, we will try to roll out a fix for this very soon.

**Comment by mj717** [comment]
Oh, sorry, I didn't know it was already a known bug. Your mod is great, thank you for your hard work!

**Comment by Cart3r1234** [comment]
No worries, Thanks for using Consistency+!  We plan on having a pre-release for 0.4 out within the next week, which should include the fix for the quartz recipe.

**Comment by Cart3r1234** [comment]
Since we've implemented the fix in the dev environments, I'm going to go ahead and close this as it will be part of the 0.4 pre release.
