### ISSUE TITLE
Purpur blocks smelt into purpur blocks

### ISSUE THREAD

**Issue by Xicad** [ConsistencyPlus/ConsistencyPlus#40]
**Describe the bug**
A clear and concise description of what the bug is. Include as much information as you can.
Purpur blocks smelt into purpur blocks, instead of smooth purpur blocks.
**Versions**
Minecraft version: 1.17
C+ version: 0.3.3
Fabric API version: 0.36.0

**Other mods**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!
architects pallete, architectury, cave biomes, custom player models, enchanting changes, extra origins, fabric api, voxelmap, incantationem, lithium, miningutility, more villagers, origins, pehkui, REI, simplebackpack, starlight, stitched snow, villagerfix, voicechat
**Logs**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/6773478/latest.log)

**To Reproduce**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Smelt a purpur block
2. Take out what you get
3. It's a purpur block

**Expected behavior**
I expected it to smelt into smooth purpur
**Screenshots**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info**
Add any other information that might be needed.

**Comment by Cart3r1234** [comment]
Thanks for the report, we'll have it fixed by the time we release a pre-release for 0.4
