### ISSUE TITLE
Polished quartz has the same recipe as block of quartz

### ISSUE THREAD

**Issue by ikak0** [ConsistencyPlus/ConsistencyPlus#44]
**Describe the bug**
Vanilla Block of Quartz is unable to be crafted as it uses the same recipe is used for polished quartz

**Versions**
Minecraft version: 1.17
Fabric API version:0.11.6

**Expected behavior**
To be able to craft a normal block of quartz

I removed most of the other questions since I don't feel they were applicable for a recipe conflict.

**Comment by Siuolthepic** [comment]
This should be fixed in the pre release of 0.4. Are you using that?

**Comment by wafflecoffee** [comment]
duplicate of #39
