### ISSUE TITLE
Known Issue: 0.4.0 causes major lag and tps drop

### ISSUE THREAD

**Issue by Cart3r1234** [ConsistencyPlus/ConsistencyPlus#51]
We are aware that 0.4.0 causes some pretty bad lag spikes.  The cause of this issue is due to the massive number of recipes that were added in 0.4.0.

We are trying to fix or minimize this issue, although we are unsure of whether or not we will be able to do anything about it.

**Comment by Cart3r1234** [comment]
Closing this because we have just released 0.4.1rc1, which should resolve or heavily reduce this issue.  Please comment on this issue or open a new one if you continue to have performance issues, and all feedback is appreciated

**Comment by TobiPeterG** [comment]
Creating a new world still takes utterly long, but loading existing worlds works without issues and at normal speed.
