### ISSUE TITLE
mod changes stone cutter recipes instead of adding them

### ISSUE THREAD

**Issue by TobiPeterG** [ConsistencyPlus/ConsistencyPlus#60]
**Describe the bug**
Hey there,

I noticed that consistency plus doesn't add stonecutter recipes, instead it changes the existing ones. Because of this, recipes added by other mods like adorn are shown as preview of the block, but a consistency plus block is crafted and visible in the output window. This happened after the update to version 0.4.0

**Versions**
Minecraft version: 1.17.1
C+ version:
Fabric API version: 0.40.0

Can this issue be confirmed?

**Comment by wafflecoffee** [comment]
> This happened after the update to version 0.4.0
We're aware this is an issue in 0.4.1-rc.1, are you sure it's present in 0.4.0 as well? I don't believe it is, because 0.4.1-rc.1 completely changes stonecutter behaviour

**Comment by TobiPeterG** [comment]
> > This happened after the update to version 0.4.0
> 
> We're aware this is an issue in 0.4.1-rc.1, are you sure it's present in 0.4.0 as well? I don't believe it is, because 0.4.1-rc.1 completely changes stonecutter behaviour

Uh, I'm not 100% sure.
I had 0.4.0 installed for just a short time, before I switched to 0.4.1-rc1 and meant it was on 0.4.0 as well, but then I'm probably wrong here

**Comment by Cart3r1234** [comment]
We’re currently working on this issue, but are unsure if it is a bug with C+ or Fabric API and what causes it.  We’ve determined that the issue is present in 0.4.1rc1, and in multiplayer only, and seems to be tags not syncing between server and client, but that’s about all we know so far.  We’ve also figured out that if you open a single player world, then join multiplayer, having synced the tags in a singleplayer world seems to temporarily fix it in multiplayer as well.

**Comment by TobiPeterG** [comment]
> We’re currently working on this issue, but are unsure if it is a bug with C+ or Fabric API and what causes it.  We’ve determined that the issue is present in 0.4.1rc1, and in multiplayer only, and seems to be tags not syncing between server and client, but that’s about all we know so far.  We’ve also figured out that if you open a single player world, then join multiplayer, having synced the tags in a singleplayer world seems to temporarily fix it in multiplayer as well.


Humm OK, that's weird, but I've exactly hit the sweet spot of the bug here, as I'm using a private server (since I can't play in single-player worlds anymore for some reasons I can't find out)

BTW. do you have an idea how to find a mod causing a too big nbt tag issue?
I've tried the good ol' remove half of the mods until it works method to determine it with a logarithmic search, but got inconsistent results and the log is telling nothing about the mod causing it, not even blame gives any hints.

Is there any smart way to debug that?

**Comment by TropheusJ** [comment]
can you provide screenshots of the issue?

**Comment by TobiPeterG** [comment]
> 
> 
> can you provide screenshots of the issue?

Umm that's a bit embrassing now and you probably think I'm mad or something, but I can't reproduce it right now, I restarted the game a few times, but it's not happening anymore.
Maybe, whatever caused it, feared that your help may identify it and disguised itself. :P
Or the mod causing it was updated and that fixed it.

Anyway, thank you for your help! :)

**Comment by TropheusJ** [comment]
oh god it is the same issue
we've been struggling with this for a bit now. we can't find a way to reproduce it. I'm convinced there's ghosts in the code.

**Comment by TropheusJ** [comment]
re-open this if it comes back

**Comment by TobiPeterG** [comment]
Oh boy, my luck is incredible, -_- I find every bug, I tell you :D (might try to be employed as bug hunter :P)
I will re-open if it happens again.

btw. I noticed that it NEVER happens on my server, only in singleplayer. Don't know if that information is worth anything.

**Comment by TropheusJ** [comment]
this is the first occurrence of it happening in singleplayer.

**Comment by TobiPeterG** [comment]
We're talking about the "too big nbt tag issue" right? 🤔

**Comment by TropheusJ** [comment]
I'm talking about the stonecutter

**Comment by TobiPeterG** [comment]
> 
> 
> I'm talking about the stonecutter

Oh okay, sorry, no, that's on the server, sorry. 😅

**Comment by TobiPeterG** [comment]
> 
> 
> can you provide screenshots of the issue?

So you want a screenshot of the stone cutter then I suspect? :D

**Comment by TropheusJ** [comment]
yes, to confirm that it is the same issue we've been having

**Comment by TobiPeterG** [comment]
![grafik](https://user-images.githubusercontent.com/19935382/132772194-b6c46604-2c9b-4770-8925-e68582b16956.png)

**Comment by TropheusJ** [comment]
yep, that's it. thanks. We're trying to find a fix but we have NO idea what causes it.

**Comment by TobiPeterG** [comment]
> 
> 
> yep, that's it. thanks. We're trying to find a fix but we have NO idea what causes it.

OK, thanks!
Well, in 0.39 it doesn't happen, so whatever you changed here, revert it. :P

**Comment by TropheusJ** [comment]
0.39? of what?

**Comment by TobiPeterG** [comment]
> 
> 
> 0.39? of what?

0.33 ofc, of c+, sorry

**Comment by Cart3r1234** [comment]
> revert it
Well the problem is that the stonecutter Changes we made in 0.4.1 were a fix for another issue that was present in 0.4/0.3.3, so reverting it would bring back another, arguably worse bug

**Comment by TobiPeterG** [comment]
> 
> 
> > revert it
> 
> Well the problem is that the stonecutter Changes we made in 0.4.1rc1 were a fix for another issue that was present in 0.4/0.3.3, so reverting it would bring back another, arguably worse bug

Uh, I'm sorry, that was more meant as a joke, not serious 😅

**Comment by TobiPeterG** [comment]
btw. other mods add stonecutter recipes as well, like Adorn and it's not happening in that mod.
Maybe their code might be of interest?

**Comment by wafflecoffee** [comment]
It's less a matter of adding them. And more a matter of their performance effects

**Comment by Cart3r1234** [comment]
The reason our stonecutter recipes cause issues is because one of our developers created a custom library that can create stonecutter recipes out of item tags, rather than having an individual json for each recipe.  This was a fix to the low performance we had due to the many thousand jsons just from stonecutter recipes.

**Comment by TobiPeterG** [comment]
> 
> 
> The reason our stonecutter recipes cause issues is because one of our developers created a custom library that can create stonecutter recipes out of item tags, rather than having an individual json for each recipe. This was a fix to the low performance we had due to the many thousand jsons just from stonecutter recipes.

OK, that's weird that this issue exists then. 🤔

**Comment by TropheusJ** [comment]
All other mods just use regular stonecutter recipes. C+ has a huge amount of blocks, so adding recipes for everything resulted in over 7k recipe files. Loading these on server start took **over a full minute of loading.** I created [a library](https://github.com/TropheusJ/stonecutter-recipe-tags) to deal with this. This library lets us define recipes with tags instead, replacing 7k files with less than 100. This bug is caused by that library, and I still have no idea how to fix it.

**Comment by TropheusJ** [comment]
I've created #61 to keep track of this issue from now on
