### ISSUE TITLE
Adding 0.4.1 to mod folder crashes other mods.

### ISSUE THREAD

**Issue by UnusedCactus** [ConsistencyPlus/ConsistencyPlus#62]
After adding the 0.4.1 update to my mod folder, other mods started crashing. This is not an issue with the 0.4.0 release.

**Versions**
Minecraft version: Fabric 1.17.1
C+ version: 0.4.1
Fabric API version: 0.37.0+ 1.17

**Other mods**
Antique Atlas
Architectury
Cloth Config
Fabric API
Fabric Language Kotlin
Gobber 2 (fabric)
Lazy DFU
Mod menu
Mythic Metals
Roughly Enough Items (REI)
Smooth Boot
Things
Trinkets
Alloy Forgery
WTHIT
Xaero's Minimap

**Logs**
*Even if the game does not crash they may be useful!*
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7140141/latest.log)
[crash-2021-09-09_18.40.38-client.txt](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7140143/crash-2021-09-09_18.40.38-client.txt)
[crash-2021-09-09_18.40.08-client.txt](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7140144/crash-2021-09-09_18.40.08-client.txt)
[crash-2021-09-09_18.40.38-client.txt](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7140171/crash-2021-09-09_18.40.38-client.txt)
(all crash reports are from trying to start Minecraft with this mod. They originate from 9/9/2021, 6:40 PM)

**To Reproduce**
Steps to reproduce the behavior.

1. Start Minecraft with Consistency+ 0.4.1, and either Gobber 2, or any MCD mod (ex. MCDAR, MCDW) (there are probably other mods like them)

**Expected behavior**
The game crashes, and blames it on one of those mods.

**Additional info**
MCD mods are Minecraft Dungeons mods. I call them MCD mods because Minecraft Dungeons is Shortened to MCD in the file name.

**Comment by wafflecoffee** [comment]
Update Fabric API to 0.40.1

**Comment by UnusedCactus** [comment]
Alright. Will try that.

**Comment by UnusedCactus** [comment]
It worked! Thank you!
