### ISSUE TITLE
Inconsistent crafting recipes of dyed terracotta bricks and some other dyed blocks

### ISSUE THREAD

**Issue by Timolino456** [ConsistencyPlus/ConsistencyPlus#68]
I wasn't sure in which category I should put this, but anyway...

**Feature**
The current crafting recipe for dyeing undyed terracotta bricks is not only really expensive in terms of dye, but also inconsistent with dyeing recipes of vanilla terracotta.
The current crafting recipe is 1 dye+ 1 undyed terracotta bricks = 1 dyed terracotta bricks
The recipe should be 1 dye + 8 undyed terracotta bricks = 8 dyed terracotta bricks, like when dyeing vanilla terracotta.
The same thing also applies to dyeing blue ice and glowstone (there could be more, not sure).

**Alternatives**
Can't think of anything.

**Additional info**
Can't think of anything.

**Comment by Cart3r1234** [comment]
Fixed the dyable recipes to output 1:8 like the vanilla ones, will be part of 0.4.1rc2 when we release it
