### ISSUE TITLE
Glowstone slabs not functioning correctly

### ISSUE THREAD

**Issue by xanthian** [ConsistencyPlus/ConsistencyPlus#76]
Sorry me again, being a pain!

Glowstone slabs aren't emitting the correct light level
See 3 screen shots below

Vanilla Glowstone light behaviour
![Screenshot 2021-10-23 171256](https://user-images.githubusercontent.com/7688001/138563812-bf376325-e741-4f99-aa72-44407e4be746.png)

Bottom slab light behaviour, seems to match that of vanilla glowstone.
![Screenshot 2021-10-23 171138](https://user-images.githubusercontent.com/7688001/138563816-42db75aa-99cc-4ad1-baaf-e5c417268e76.png)

Top slab only, no light emission at same level
![Screenshot 2021-10-23 171230](https://user-images.githubusercontent.com/7688001/138563813-81f19bd6-fccd-4a49-9cbf-2df763429282.png)

Top slab will however emit light downwards 
![Screenshot 2021-10-23 172025](https://user-images.githubusercontent.com/7688001/138563992-0ff5293a-ae43-4bfb-b25b-44d832a02484.png)

Bottom slab, does not
![Screenshot 2021-10-23 172050](https://user-images.githubusercontent.com/7688001/138564006-88794e63-2ce4-4744-99a6-15b51926981e.png)

**Comment by Cart3r1234** [comment]
Closing this since we fixed it for the glowstone sets, and 0.4.1 is releasing in a few days.  May still happen with crying obsidian slabs/stairs if we don't do anything about it before then, but its a small enough thing where it shouldn't impact anything if left unfixed for a bit longer
