### ISSUE TITLE
mod causing "java.lang.RuntimeException: Tried to read NBT tag that was too big" and kick out of world

### ISSUE THREAD

**Issue by IceyGH** [ConsistencyPlus/ConsistencyPlus#77]
**Describe the bug**
When I start a world the world will initially start to load but as soon as it reaches 100% it will kick me out of the world and just say "connection lost". after looking at the legs I saw "java.lang.RuntimeException: Tried to read NBT tag that was too big" and through the process of elimination found out that consitenacy+ causes this.

**Versions**
Minecraft version: 1.17.1
C+ version: tested on 0.4.0 and 0.4.1rc.3
Fabric API version: 0.41.0

**Other mods**
Full List In Mod Files

**Logs**
https://pastebin.com/2yRZdQJL

**To Reproduce**

All that needs to be done is to load a world with multiple mods and with Consistency+ installed.

**Comment by TropheusJ** [comment]
see #63
