### ISSUE TITLE
Consistency Table

### ISSUE THREAD

**Issue by githubUser947** [ConsistencyPlus/ConsistencyPlus#80]
I suggest a new block called a Consistency Table.

If interacted with, It will open a GUI which allows you to turn a Consistency-supported block into its varients. This may or may not have a recipe. Creative only or Survival-friendly.

Textures:

![consistency_table_side](https://user-images.githubusercontent.com/87000530/141673956-d7469c46-f79f-4682-b832-f3b80137de00.png)

![consistency_table_front](https://user-images.githubusercontent.com/87000530/141673964-a4229de7-e122-43f5-b1ef-6de458c572a8.png)

![consistency_table_top](https://user-images.githubusercontent.com/87000530/141673906-79238d02-7da7-4e46-880b-00ccfae47edd.png)

![consistency_table_bottom](https://user-images.githubusercontent.com/87000530/141673975-1261f6a7-74bb-4967-a561-ebdde54ac06d.png)

**Comment by githubUser947** [comment]
And if possible, a carver tool that will carve the block the player is looking at

Recipe: a  i  a
            a  i  a
            a  l  a
a - air
i - iron ingot
l - leather

**Comment by Cart3r1234** [comment]
Right now, stonecutters basically function as you described the Consistency Table - you can use stonecutters to craft a block into any other form of that same material, including slabs/stairs/walls/gates, so having a special utility block that does the same thing seems unnecessary.

As for a tool that can carve blocks, its an interesting idea, but not something that we would consider adding to the base mod.  There is another mod that does something similar with shapes (stairs, slabs, etc), so maybe at some point we could make an addon to C+ that adds tools with similar functions, like a carver or chisel.
