### ISSUE TITLE
Missing Sandstone Recipes

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ConsistencyPlus/ConsistencyPlus#82]
**Describe the bug**
In my 1.18 RC3 pack, [99 Mods on the Wall: Fabric Edition](https://github.com/ClaudiusMinimus/99-Mods-on-the-Wall-Fabric-Edition/releases/tag/v1.18.0-RC-0.19.0) I have noticed the following recipes are either broken or missing:
Cobbled Sandstone and Cobbled Red Sandstone: Stairs, Slabs, and Walls.

Please note the pack is not released on Curseforge yet since they don't allow Snapshot mod packs, even though it looks like the should.

**Versions**
Minecraft version: 1.18-RC1
Fabric Loader: 0.12.5
Fabric API version: 

**Other mods**
Mods:
  [✔️] Adorn-3.0.0-rc.1+1.18-rc3-fabric
  [✔️] apples-carrots-1.3.1
  [✔️] appleskin-fabric-mc1.17-2.1.3
  [✔️] architects-palette-fabric-1.3-1.18-rc3
  [✔️] architectury-3.0.39
  [✔️] autoconfig1u-3.3.1
  [✔️] better-recipe-book-1.5.4-1.18
  [✔️] blockus-2.3.1+1.18-pre5
  [✔️] BountifulFabric-2.0.1
  [✔️] camerautils-1.18-rc1-1.0.0
  [✔️] canvas-fabric-mc118-1.0.2223
  [✔️] cloth-config-6.0.42-fabric
  [✔️] conjuring-1.0.12+1.18
  [✔️] consistency_plus-fabric-0.4.2+RC.1+1.17
  [✔️] Couplings-1.5.1+1.17
  [✔️] craftingpad-21w40a-1.0.6
  [✔️] CraftPresence-Fabric-21w38a-Release-1.8.8
  [✔️] cullleaves-2.3.2
  [✔️] CustomWindowTitle-Fabric-1.17.1+v1.1.1
  [✔️] cyanide-fabric-1.18-pre6-2.0.2
  [✔️] CyberPermissions-1.3-fabric
  [✔️] dankstorage-2.2.1-1.17.1
  [✔️] dark-enchanting-0.6.0-1.18
  [✔️] deepslatecutting-21w40a-1.3.0
  [✔️] DefaultSettings-1.18.x-3.1.0
  [✔️] DynamicSoundFilters-1.3.0+1.18
  [✔️] EditSign-1.17.1-2.2.3
  [✔️] EmeraldTools-Fabric-1.18-rc3-1.3.27
  [✔️] essential_commands-0.17.0-mc1.17.1
  [✔️] EssentialGUI-1.7+21w43a
  [✔️] extshape-1.3.1-mc1.17+
  [✔️] fabric-api-0.43.1+1.18
  [✔️] fabric-furnaces-2.0.1-1.17
  [✔️] fabric-language-kotlin-1.7.0+kotlin.1.6.0
  [✔️] fabric-language-scala-2.0.0+scala.3.0.2
  [✔️] geckolib-fabric-1.18-3.0.20
  [✔️] get-off-my-lawn-1.17-1.4.0-beta
  [✔️] giftit-1.5.0+mc1.18-rc3
  [✔️] glassential-fabric-1.3.0
  [✔️] Gobber2-Fabric-1.18-rc1-2.5.48
  [✔️] goblin-traders-1.4.0
  [✔️] GreaterEye-Fabric-1.18-pre5-1.3.13
  [✔️] grind-enchantments-1.4.0+1.17.1
  [✔️] grizzlybear-1.17-1.2.0
  [✔️] Harvest-fabric-1.16.1-1.0.1
  [✔️] here-be-no-dragons-1.0.0
  [✔️] InventoryProfilesNext-fabric-1.18-1.1.8
  [✔️] Kambrik-3.0.0
  [✔️] lambdynamiclights-2.0.2+1.17
  [✔️] light-overlay-6.0.3
  [✔️] Mambience-3.2.0+1.18
  [✔️] Mesh-0.18.0-alpha
  [✔️] MiningDimensions_Fabric-1.18-rc1-1.2.31
  [✔️] miningutility-1.2+1.18-pre1
  [✔️] Mo-Glass-1.5-MC1.18-rc3
  [✔️] MobCatcher-Fabric-1.18-pre6-1.1.14
  [✔️] modmenu-3.0.0
  [✔️] MoreGems-Fabric-1.18-rc3-1.3.47
  [✔️] mousewheelie-1.8.0+mc1.18-pre5
  [✔️] NE-1.18-Fabric-1.2.0
  [✔️] notenoughcrashes-4.1.2+1.18-rc3-fabric
  [✔️] okzoomer-5.0.0-beta.2+1.17
  [✔️] OverpoweredPickles-Fabric-1.18-pre7-1.3.4
  [✔️] owo-lib-0.3.7+1.18
  [✔️] Patchouli-1.17.1-58-FABRIC
  [✔️] Paxi-Fabric-1.17-1.2.2
  [✔️] projectsavethepets-2.0.0-beta.1+2021.19c19369c0
  [✔️] quartz-elevator-2.0.0-beta1-1.18-pre5
  [✔️] redstone-bits-1.6.0+fabric-mc1.18
  [✔️] reinforced-barrels-1.0.4+1.18
  [✔️] reinforced-chests-1.0.4+1.18
  [✔️] reinforced-shulker-boxes-1.1.3+1.18
  [✔️] repurposed_structures_fabric-3.0.2+1.18-rc3
  [✔️] ResourcefulTools-Fabric-1.18-pre6-1.2.23
  [✔️] RoughlyEnoughItems-fabric-7.0.339
  [✔️] shulkerboxtooltip-3.0.5-beta.1+1.18-pre5
  [✔️] SimpleBackpack_Fabric-1.18-rc3-1.2.19
  [✔️] storagebox-1.0.4-1.17.1
  [✔️] TheVeggieWay_Fabric-1.18-pre6-1.2.20
  [✔️] things-0.2.7+1.18
  [✔️] tomsstorage-1.1.18
  [✔️] trapexpansion-1.3.3+fabric-mc1.17
  [✔️] TreeAxe-Fabric-1.18-rc3-1.1.21
  [✔️] trinkets-3.0.4
  [✔️] UncraftingTable-1.0.0-1.17.1
  [✔️] WardBlocks-Fabric-1.18-pre5-1.2.16
  [✔️] wmitaf-fabric-mc1.18-2.1.4
  [✔️] wraith-alloy-forgery-2.0.6+1.18
  [✔️] xp_storage-1.4.2+1.17.1
  [✔️] xpstorage_trinkets-0.1+1.17.1
  [✔️] yosbr-0.1.1
  [✔️] youre-in-grave-danger-1.2.2
  [✔️] YungsApi-1.17-Fabric-19

**Logs**
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7612706/latest.log)
[MultiMC-0.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7612707/MultiMC-0.log)

**To Reproduce**
1. Open REI and look for the blocks mentioned.

**Comment by wafflecoffee** [comment]
Damn you're dedicated. Good on you.

**Comment by Cart3r1234** [comment]
Seems to also affect Soul Sandstone.  I'll take care of it in a bit

**Comment by Cart3r1234** [comment]
Will be fixed in the next release candidate.  Thanks for reporting!

**Comment by Siuolthepic** [comment]
I assume you have the fix ready on your end Carter?

**Comment by Cart3r1234** [comment]
> I assume you have the fix ready on your end Carter?

I already committed it
