### ISSUE TITLE
Compatibility level set to JAVA_16

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ConsistencyPlus/ConsistencyPlus#85]
**Describe the bug**
Intermittently it seems by setting the Compatibility level set to JAVA_16 causes the server to fail to launch. I have had this happen with other mods in my pack and when it is changed to JAVA_17 it works fine.

**Versions**
	- fabricloader 0.12.5
	- java 17
	- minecraft 1.18-rc.3
	- architectury 3.0.39
	- consistency_plus 0.4.2+RC.1+1.17
	- fabric 0.43.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cd14
	- fabric-api-lookup-api-v1 1.3.5+3ac43d9514

**Logs**
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7620497/latest.log)

**To Reproduce**
1. Launch server
2. Fail to launch

**Expected behavior**
Should launch consistently

**Comment by Siuolthepic** [comment]
I'll work alone a fix after next period

**Comment by Siuolthepic** [comment]
Alright, are you available to help debug this? I did some quick testing and I am able to perfectly launch on RC4 with Java 17.

**Comment by Siuolthepic** [comment]
I have a feeling this could of easily been just a compilation issue or the alike, since it works on my machine, could you try this recompiled version?

[consistency_plus-0.4.2+1.17-fabric.zip](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7620973/consistency_plus-0.4.2%2B1.17-fabric.zip)

**Comment by ClaudiusMinimus** [comment]
It was an intermittent thing. I tested your recompiled version and the server launched fine. Are you testing in the client or with a server install?

**Comment by Siuolthepic** [comment]
I tested it on a fresh server install.

**Comment by ClaudiusMinimus** [comment]
Then it is likely fixed. Thanks!

**Comment by ClaudiusMinimus** [comment]
I just ran a test with the old and the recompiled files and only difference I can see in the logs is this
> - libcd 3.0.3+1.16.3[15:46:33] [main/WARN]: Mod `consistency_plus` (0.4.2+RC.1+1.17) does not respect SemVer - comparison support is limited.
So it looks like your recompiled version fixes this warning

**Comment by wafflecoffee** [comment]
It's an irrelevant log line. If you encounter this issue again, reopen the issue, but I'll say it's resolved for now

**Comment by ClaudiusMinimus** [comment]
I would like to say how grateful I am for the promptness you address issues!
Thank you,
CM
