### ISSUE TITLE
Gates should be a bit more full

### ISSUE THREAD

**Issue by Micalobia** [ConsistencyPlus/ConsistencyPlus#86]
**Feature**

Essentially, the current stone variant gates feel small and thin in comparison to the walls they're supposed to parallel and look goofy when used. Wooden gates don't have that issue, meshing with their parallel perfectly.

**Alternatives**

Just a modeling thing

**Additional info**

N/A

**Comment by Siuolthepic** [comment]
Alright, let me explain my reasoning on why they are "thin"

In short, you either have thin sides, or seemingly look like you have to squish through the gate, the 4x4 pixel post was the best I could do within reason.

The better approach to fixing this all is not associating the gates to walls, but rather to a fence.
@Cart3r1234 I know we had discussed the idea of fences in C+, but whats your 2 cents?

**Comment by Cart3r1234** [comment]
Fences could happen at some point, as nether bricks are currently the only set with both a wall and a fence.  
When we first made gates, I threw the idea out of making them a few pixels taller than they are now, which is another 'solution.'  As they are now, gates don't _need_ to change, but if may be something worth looking into.

For now I'm going to close this, but I'll tag it with under review as it is something we may look into in coming updates.
