### ISSUE TITLE
Crash at creating a new world

### ISSUE THREAD

**Issue by ghost** [ConsistencyPlus/ConsistencyPlus#87]
**Describe the bug**
Crash at creating a new world after updating C+ from 0.3 to 0.4.2

**Versions**
Minecraft version: 1.16.5
C+ version: 0.4.2
Fabric API version: 0.43.0+1.16 (Edited by Siuol the reflect the actual version of Fabric API used.)

**Other mods**
[crash-2021-12-04_13.23.09-server.txt](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7653380/crash-2021-12-04_13.23.09-server.txt)

**Logs**
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7653378/latest.log)

**To Reproduce**
1. Updating C+ from 0.3 to 0.4.2
2. Start Minecraft
3. Create new world

**Comment by TropheusJ** [comment]
install [XL packets](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) and try again

**Comment by KuysKyle3212** [comment]
Already have it on the pack, you can see it in the logs that I have it installed

**Comment by wafflecoffee** [comment]
https://media.discordapp.net/attachments/808737252275519528/834093874288525332/Error_Go_Brrrrr.mp4

**Comment by Pythagoras-314** [comment]
wtf that's not helpful

**Comment by wafflecoffee** [comment]
Looking at your latest.log. I see no reason why your client would ever load in the first place. With or without C+. It's cursed to hell. Burn it with fire.

**Comment by Siuolthepic** [comment]
Alright, so I don't think its SPECIFICALLY us, but I am genuinely curious on why this issue arises, where its from, and the alike.

What I am saying is that we should probably keep this up as something to research, but this isn't considered an issue with us.
Under absolutely 0 circumstances would it make sense that upgrading specifically C+ to a newer version of itself would cause that. Most likely, its some interaction with another mod, or the total amount of additions.

For now, its fine if you take C+ out of the modpack, but you may wanna try removing other big block mods (Such as Blockus) or mods that stopped seeing love and attention from their devs (Such as Kyanite) and seeing if that also fixes it.

If you find a "Minimum mods to get C+ to crash" list please inform us.

**Comment by Cart3r1234** [comment]
For now I'm closing this since we haven't had any similar (unsolved) reports of crashing with large modpacks in a while, and nothing has happened with it since December.  I'll leave the current labels on the issue for if we come back to it at some point.  

If there is still interest in looking into this, try upgrading to versions past 0.4.2 (0.4.3 for 1.16-1.18.1, or 0.5.0-rc.3 for 1.18.2) to see if it still happens.
