### ISSUE TITLE
Obsidian additions are pushable by pistons.

### ISSUE THREAD

**Issue by JJSax** [ConsistencyPlus/ConsistencyPlus#88]
**Describe the bug**
Consistency+ has a large list of obsidian blocks.  I have tested 2 gates and polished obsidian and they all are able to be pushed by pistons despite vanilla obsidian being unpushable.  Not very consistent ;)

**Versions**
Minecraft version: 1.18.1
C+ version: 0.4.2
Fabric API version: 0.12.12

**Other mods**
<details>
<summary>It's somewhat long and probably not useful, but click to expand.</summary>
3dSkinLayers-Fabric-1.3.1.jar<br/>
AdditionalAdditions-3.0.1.jar<br/>
appleskin-fabric-mc1.18-2.2.0.jar<br/>
architectury-3.2.51.jar<br/>
balm-fabric-2.3.0+0.jar<br/>
bclib-1.1.2.jar<br/>
BeaconOverhaul-1.5.0+1.18.jar<br/>
better-nether-6.0.6.jar<br/>
betterbeaconplacement-fabric_1.18.x-1.4.jar<br/>
betterconduitplacement-fabric_1.18.x-1.3.jar<br/>
BetterF3-1.2.1-Fabric-1.18.jar<br/>
blur-2.4.1.jar<br/>
boatcontainer-1.0.4.jar<br/>
carpet-extra-1.18-1.4.56.jar<br/>
carrier-1.9.0.jar<br/>
cherishedworlds-fabric-2.0.1-1.18.jar<br/>
cleancut-1.18-4.0-fabric.jar<br/>
cloth-config-6.1.48-fabric.jar<br/>
collective-fabric-1.18.x-3.14.jar<br/>
consistency_plus-0.4.2+1.17-fabric.jar<br/>
continuity-1.0.3+1.18.jar<br/>
craftingtweaks-fabric-1.18-13.0.0.jar<br/>
Croptopia-1.18-FABRIC-1.7.4.jar<br/>
doubledoors-fabric_1.18.x-3.1.jar<br/>
dragonloot-1.0.9.jar<br/>
EasyMagic-v3.2.0-1.18.1-Fabric.jar<br/>
enchantment-lore-1.2.3+MC1.18-1.18.1.jar<br/>
end-goblin-traders-1.4.2.jar<br/>
enhancedcelestials-1.18-2.0.6.jar<br/>
EntityCulling-Fabric-1.3.3.jar<br/>
fabric-api-0.44.0+1.18.jar<br/>
fabric-carpet-1.18-1.4.56+v211130.jar<br/>
fabric-seasons-1.3-BETA+1.18.jar<br/>
fallingleaves-1.8.1+1.18.1.jar<br/>
farsight.fabric-1.18-1.5.jar<br/>
fastfurnace-1.18-4.jar<br/>
ForgeConfigAPIPort-v3.1.0-1.18.1-Fabric.jar<br/>
geckolib-fabric-1.18-3.0.23.jar<br/>
goblin-traders-1.4.1.jar<br/>
graves-1.2.2+1.18.jar<br/>
ImprovedHoes-Fabric-1.18.1-2.1.jar<br/>
indium-1.0.2-alpha1+mc1.18.jar<br/>
inventory-control-tweaks-1.3.12+MC1.18-1.18.1.jar<br/>
InventoryProfilesNext-fabric-1.18-1.2.1.jar<br/>
iris-mc1.18.1-1.1.3.jar<br/>
ITO-1.01.jar<br/>
konkrete_fabric_1.3.2_MC_1.18.jar<br/>
kubejs-fabric-1801.4.0-build.245.jar<br/>
litematica-fabric-1.18.0-0.0.0-dev.20211203.013300.jar<br/>
malilib-fabric-1.18.0-0.10.0-dev.26.jar<br/>
map-atlases-1.3.1-v1.18.jar<br/>
megane-6.1.2.jar<br/>
modmenu-3.0.1.jar<br/>
mores-1.2.7.jar<br/>
morevillagers-FABRIC-1.18-3.0.0.jar<br/>
mousewheelie-1.8.0+mc1.18-pre5.jar<br/>
okzoomer-5.0.0-beta.3+1.17.1.jar<br/>
oxidized-1.5.1.jar<br/>
PickUpNotifier-v3.1.0-1.18.1-Fabric.jar<br/>
PuzzlesLib-v3.1.1-1.18.1-Fabric.jar<br/>
repurposed_structures_fabric-3.1.10+1.18.1.jar<br/>
rhino-fabric-1800.1.6-build.81.jar<br/>
RoughlyEnoughItems-7.1.356.jar<br/>
sodium-extra-mc1.18-0.3.7.jar<br/>
sodium-fabric-mc1.17.1-0.3.3+build.8.jar<br/>
sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar<br/>
Terralith_v2.0.5_~_Fabric+Forge.jar<br/>
toms_storage-1.18-1.1.19.jar<br/>
treeharvester-fabric_1.18.x-4.1.jar<br/>
TWM[1.18.x]<br/>
wanderingcollector-1.0.3+mc1.18-rc3.jar<br/>
wraith-waystones-2.3.5.jar<br/>
wthit-fabric-4.4.0.jar<br/>
XaerosWorldMap_1.18.8_Fabric_1.18.jar<br/>
Xaeros_Minimap_21.22.6_Fabric_1.18.jar<br/>
</details>

**Logs**
*Even if the game does not crash they may be useful!*
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7748333/latest.log)

**To Reproduce**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. place C+ obsidian block in front of a piston
2. power said piston
3. Witness movement

**Expected behavior**
No movement

**Comment by Siuolthepic** [comment]
Why is it back.
Why is it back.
Why is it back.
Why is it back.
Why is it back.
Why is it back.
Why is it back.
Why is it back.
Why is it back.
Why is it back.
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Siuolthepic** [comment]
Closed, gone, eliminated in newest commit.

This issue, never was a thing, never happened, never ever, nope, 0, no issue, nothing happened, we are extremely professional.
