### ISSUE TITLE
Cobbled Blackstone - No Stonecutter Recipes

### ISSUE THREAD

**Issue by xanthian** [ConsistencyPlus/ConsistencyPlus#92]
Nothing can be done with Cobbled Blackstone on the Stone Cutter.

![image](https://user-images.githubusercontent.com/7688001/147600759-3c7a91dc-5f5b-476e-b49f-8043c48b613a.png)

MC 1.17.1
Fabric
C+ 0.43

**Comment by Siuolthepic** [comment]
Most recent commit fixes this, I'll also give a datapack for a temporary fix as we will probably fix this in 0.5.0

**Comment by Siuolthepic** [comment]
Datapacks with Fixes
[CobbledBlackstoneFix1.18.zip]
(https://github.com/ConsistencyPlus/ConsistencyPlus/files/7786236/CobbledBlackstoneFix1.18.zip)
[CobbledBlackstoneFix1.17.zip](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7786237/CobbledBlackstoneFix1.17.zip)
[CobbledBlackstoneFix1.16.zip](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7786240/CobbledBlackstoneFix1.16.zip)
