### ISSUE TITLE
Dirt and grass slabs, stairs and walls do not drop anything when mined

### ISSUE THREAD

**Issue by Timolino456** [ConsistencyPlus/ConsistencyPlus#93]
**Describe the bug**
Dirt and grass slabs, stairs and walls do not drop anything when mined. Even with silk touch they don't. Sand, red sand and gravel (chosen because of similar hardness and same mining tool) slabs, stairs and walls do though.
I already lost 4 very valuable dirt slabs in my survival world. :(

**Versions**
Minecraft version: 1.18 (not 1.18.1 if it makes any difference)
C+ version: 0.4.3 for 1.18
Fabric API version: 0.45.0

**Other mods**
I'm using MultiMC, hence the ".disabled" files for disabled mods
![image](https://user-images.githubusercontent.com/38137599/147853903-64fdd09b-a86f-44ff-b4a6-0f4c28ee09ff.png)

**Logs**
Don't be surprised, I believe the Sodium alpha has a memory leak issue, it's quite present here lol
[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7797831/latest.log)

**To Reproduce**
1. Place one of the mentioned blocks
2. Mine it
3. Cry

**Expected behavior**
They should drop themselves. I don't see why they shouldn't.

**Additional info**
Can't think of anything.

**Comment by Cart3r1234** [comment]
Just tested it and yeah, looks like they are missing loot tables.  Thanks for the report!

**Comment by Siuolthepic** [comment]
Oh yeah I fixed this in my newest commit :)
