### ISSUE TITLE
Causes other mods to prevent entering the world

### ISSUE THREAD

**Issue by UnusedCactus** [ConsistencyPlus/ConsistencyPlus#94]
**The Bug**: When installed, this causes certain other mods (ex. Chipped, Super Block World since around ver. 1.0.11) to exit to the server menu when trying to enter the world. Does not cause problems on its own.

**Versions**
Minecraft version: Latest Fabric release (1.17.1 and 1.18.1)
C+ version: Latest (by writing date)
Fabric API version: Latest (by writing date)

**Other mods**
Chipped
Fabric API
Gecko Lib
Super Block World (Might have changed in 1.0.14)

**Logs**
All the logs show that the world loads, runs into a major error, then exits to server menu. Nothing else

**To Reproduce**
1. Install mods
2. Start up Minecraft
3. Try to load a world through any means

**Expected behavior**
The game Loads, however doesn't let you enter into the world.

**Screenshots**
can't

Because this bug depends on Consistency+, and doesn't change based on the mod, I figure it might be an issue with C+ and not those mods. There are no connections in which mods do this.

**Comment by Siuolthepic** [comment]
Do you have XL Packets installed? Try seeing if that helps.

**Comment by Cart3r1234** [comment]
This issue will be closed if there's no response within the next week - There's no log attached, and no response to Siuol asking about trying XL packets, and that was back in January.

**Comment by Cart3r1234** [comment]
Closing due to lack of response.  May revisit this at a later date and try and reproduce the issue, however this is not a current priority
